### ISSUE TITLE
feat: quick first indexing

### ISSUE THREAD

**Issue by bonustrack** [checkpoint-labs/checkpoint#168]
~~One idea to speedup indexing on first sync or when adding new contract would be to create a server using Checkpoint which index all the checkpoints for all the contracts on StarkNet to allow server running Checkpoint instance to seed checkpoints from it.~~

Another approach would be to use the provider function `getEvents` for multiple blocks at once to find checkpoints and seed them into the db

**Comment by bonustrack** [comment]
Another approach would be to use the provider function `getEvents` for multiple blocks at once to find checkpoints and seed them into the db

**Comment by Sekhmet** [comment]
> Another approach would be to use the provider function getEvents for multiple blocks at once to find checkpoints and seed them into the db

For this, you think we should checkpoint all events, even those unrelated for the indexer (because we won't know which ones are related).

This might end up with lots of data to store, there are currently 3.5 million events on goerli2, 82 million on goerli1, if we assume 32 bytes per record (address is 32 bytes on its own, ignoring block number to adjust for possible compression), this means:
goerli2: 112 GB
goerli1: 2.6 TB

This is for full history, so it's unlikely that most applications will need to store this much, but it doesn't scale to have all apps store it locally.

This also won't help with global_events tracking as we would need event_hash/blockNumber checkpoints then, which will increase size significantly too if we handle that.

**Comment by anhlam2234** [comment]
> ~~One idea to speedup indexing on first sync or when adding new contract would be to create a server using Checkpoint which index all the checkpoints for all the contracts on StarkNet to allow server running Checkpoint instance to seed checkpoints from it.~~
> 
> 
> 
> Another approach would be to use the provider function `getEvents` for multiple blocks at once to find checkpoints and seed them into the db
